[package]
name = "zero-knowledge-proofs"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.14.4"
tokio = { version = "1.53.1", features = ["full"] } # async rust runtime
tonic = "0.14.6"
tonic-prost = "0.14"

[build-dependencies]
tonic-prost-build = "0.14"


[[bin]]
name = "server"
path = "./src/server.rs"


[[bin]]
name = "client"
path = "./src/client.rs"